volumes:
  jenkins_home:
  workspace:

version: '3.8'

services:

  jenkins:
    # Si se levanta por primera vez el Jenkins, habrá que configurarlo
    # - Instalar plugins sugeridos
    # - Instalar plugin de Allure
    # - Configurar Allure Commandline
    # - Añadir el agente
    # - Configurar Job (que ejecute solo en el agente playwright)
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  agent:
    # Si se levanta por primera vez el agente, habrá que vincularlo al jenkins
    # - Ejecutar el comando curl que nos proporciona el jenkins
    build: .
    container_name: playwright-agent
    restart: always
    depends_on:
      - jenkins
    volumes:
      - workspace:/var/jenkins/workspace